### ISSUE TITLE
Help with cloudflare tunnel

### ISSUE THREAD

**Issue by ciocan** [cloud-agnost/agnost-gitops#20]
Im trying to use it with Cloudflare tunnel.

Cloudflare Operator is up and running - I have other apps working fine.
https://github.com/adyanth/cloudflare-operator/

```bash
microk8s kubectl apply -f - <<EOF
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: agnost-console-tunnel
  namespace: agnost
subjects:
  - name: studio
    spec:
      fqdn: agnost.mysite.com
      path: ^/studio
  - name: platform
    spec:
      fqdn: agnost.mysite.com
      path: ^/api
  - name: sync
    spec:
      fqdn: agnost.mysite.com
      path: ^/sync
tunnelRef:
  kind: ClusterTunnel
  name: microk8s-cluster-tunnel
EOF

```

I used Minikube Installation with these values:

```yaml
ingress-nginx:
  enabled: false
  namespaceOverride: ingress
cert-manager:
  enabled: false
  namespace: cert-manager
agnost-webhook:
  certManager:
    namespace: cert-manager
    serviceAccountName: cert-manager
```

The studio page loads at https://agnost.mysite.com/studio
but i see 404 inconsole for api

GET https://agnost.mysite.com/api/v1/cluster/setup-status 404 (Not Found)

In the platform pod logs I see this:
2025-06-25T14:09:00.297Z info: GET (404) 0.4ms /api/v1/cluster/setup-status

What needs to be changed to make it work?
